#!/bin/bash
## Add this file in /etc/cron.weekly/ or /etc/cron/monthly, etc.
## Customize your scripts' path.
## You can install anacrontab so it also download at next power up if 
## the pc wasn't on on the planned day.
cd /home/c/t/i/pads/arch/
bash etherpad-backups.sh automatic
